version: '3.7'

services:
  mc:
    build:
      context: .
      dockerfile: Dockerfile
    image: mc
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80
